# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


- task: RunFromFileSystemTask@1
  inputs:
    testPathInput: 'C:\AutomatedTests\AreaManager101'
- task: ReportTask@1
